@baseUrl=http://localhost:4000/api
@resourses=products


###
# @name getAll
GET {{baseUrl}}/{{resourses}}

###
# @name update
PATCH {{baseUrl}}/{{resourses}}/74bb3b1b-06f4-4020-abe5-8fbf9b8caf98
Content-Type: application/json

{
  "name": "Haha1"
}

###
DELETE {{baseUrl}}/{{resourses}}/74bb3b1b-06f4-4020-abe5-8fbf9b8caf98

###
# @name add
POST {{baseUrl}}/{{resourses}}
Content-Type: application/json

{
  "name": "Thich bia"
}

###
# @name sort
GET {{baseUrl}}/{{resourses}}?price_gte=800

###
# @name search
GET {{baseUrl}}/{{resourses}}?description_like=modern

###
# @name pagination
GET {{baseUrl}}/{{resourses}}?_page=1&_limit=5
